version: '4.7.1-SNAPSHOT+AppVeyor.{build}'
os: Visual Studio 2015
branches:
  only:
  - master
build_script:
  - mvn -DskipTests install -q --batch-mode 
test_script:
  - mvn test -Dantlr.testinprocess=true -DJDK_SOURCE_ROOT=../runtime/Java/src -Dperformance.package= -q --batch-mode
